require("options")
require("clipboard-setup")
require("packer-setup")
require("vim-airline-setup")
require("telescope-setup")
require("lsp-zero-setup")
require("shortcuts")
require("treesitter-setup")
